"""Identity for Cerebro — who is making this request.

§6.2 established that the server assigns authorship and the caller never claims it. §6.3 adds the
missing half: an external agent needs a way to be *itself*. Without it the only authenticated
identity is the human, so Claude, Antigravity and Codex sit in channels they cannot speak in, and
the tempting shortcut is to let automation borrow Dante's principal — which is impersonation with
a cutover attached.

§6.3 Amendment: Absence of credentials is NOT an identity. The human principal comes only from a
positive session token issued by the server when serving the UI to a loopback client, NEVER from
the absence of a header. An unauthenticated request is refused with 401.
"""

import hmac
import os
import secrets
from dataclasses import dataclass
from pathlib import Path
from fastapi import Cookie, Header, HTTPException, Request

TOKEN_PREFIX = "CEREBRO_AGENT_TOKEN_"
TOKEN_BYTES = 32
HUMAN_ID = "dante"
SESSION_COOKIE_NAME = "cerebro_session"


@dataclass(frozen=True, slots=True)
class Principal:
    """Who the server believes is speaking. Never built from client-supplied data."""

    id: str
    kind: str = "user"  # 'user' | 'agent'
    name: str = "Dante"

    @property
    def is_agent(self) -> bool:
        return self.kind == "agent"

    @property
    def author_kind(self) -> str:
        """What `messages.author_kind` becomes for anything this principal writes."""
        return "agent" if self.is_agent else "user"


HUMAN = Principal(id=HUMAN_ID, kind="user", name="Dante")


def redact(token: str) -> str:
    """Safe to log. Enough to correlate, not enough to use."""
    return f"{token[:4]}…{token[-2:]}" if len(token) > 8 else "…"


def _env_key(agent_id: str) -> str:
    return TOKEN_PREFIX + agent_id.upper().replace("-", "_")


class SessionStore:
    """Server loopback session token management for the human owner (§6.3)."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    def issue(self) -> str:
        """Get or create the active server session secret."""
        if self.path.exists():
            try:
                secret = self.path.read_text(encoding="utf-8").strip()
                if secret:
                    return secret
            except OSError:
                pass
        secret = secrets.token_urlsafe(TOKEN_BYTES)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix(".tmp")
        tmp.write_text(secret, encoding="utf-8")
        os.replace(tmp, self.path)
        return secret

    def validate(self, token: str | None) -> bool:
        """Validate a session token against the stored secret in constant time."""
        if not token:
            return False
        known = self.issue()
        return hmac.compare_digest(token, known)


class TokenStore:
    """Agent bearer tokens, in an env file outside version control."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    def _read(self) -> dict[str, str]:
        """agent_id -> token. A malformed line is skipped rather than fatal."""
        out: dict[str, str] = {}
        try:
            text = self.path.read_text(encoding="utf-8")
        except OSError:
            return out
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            if key.startswith(TOKEN_PREFIX) and value.strip():
                out[key[len(TOKEN_PREFIX):].lower().replace("_", "-")] = value.strip()
        return out

    def _write(self, tokens: dict[str, str]) -> None:
        """Atomic replace: a crash mid-write must not leave every agent unable to authenticate."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Cerebro agent bearer tokens. Never commit this file.",
            "# Generated by `cerebro token issue`; see architecture §6.3.",
        ]
        lines += [f"{_env_key(agent)}={token}" for agent, token in sorted(tokens.items())]
        tmp = self.path.with_suffix(self.path.suffix + ".tmp")
        tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(tmp, self.path)

    def issue(self, agent_id: str) -> str:
        """Mint a token, replacing any existing one for that agent."""
        token = secrets.token_urlsafe(TOKEN_BYTES)
        tokens = self._read()
        tokens[agent_id] = token
        self._write(tokens)
        return token

    def revoke(self, agent_id: str) -> bool:
        tokens = self._read()
        if agent_id not in tokens:
            return False
        del tokens[agent_id]
        self._write(tokens)
        return True

    def agents(self) -> list[str]:
        """Agent ids holding a token. Deliberately returns no token material."""
        return sorted(self._read())

    def get(self, agent_id: str) -> str | None:
        """Return the bearer token for agent_id, or None if not found."""
        return self._read().get(agent_id)

    def resolve(self, token: str) -> str | None:
        """Return the agent id for a token, or None. Constant-time scan across all entries."""
        if not token:
            return None
        found: str | None = None
        for agent_id, known in self._read().items():
            if hmac.compare_digest(token, known):
                found = agent_id
        return found


def parse_bearer(header: str | None) -> str | None:
    """Extract the token from an Authorization header, or None if absent."""
    if not header:
        return None
    scheme, _, value = header.strip().partition(" ")
    if scheme.lower() != "bearer" or not value.strip():
        return None
    return value.strip()


def get_token_store() -> TokenStore:
    from cerebro.config import settings
    return TokenStore(settings.data_dir / ".secrets.env")


def get_session_store() -> SessionStore:
    from cerebro.config import settings
    return SessionStore(settings.data_dir / ".session.token")


def principal_for(token: str | None, tokens: TokenStore) -> Principal:
    """Resolve an agent bearer token to an agent Principal. Absent token returns HUMAN."""
    if token is None:
        return HUMAN
    agent_id = tokens.resolve(token)
    if agent_id is None:
        raise PermissionError("unrecognised agent token")
    return Principal(id=agent_id, kind="agent", name=agent_id)


async def get_current_principal(
    request: Request,
    authorization: str | None = Header(default=None),
    cerebro_session: str | None = Cookie(default=None),
) -> Principal:
    """Resolve who is speaking, per §6.2 and amended §6.3.

    1. Authorization Bearer token -> agent Principal.
    2. cerebro_session cookie -> Dante HUMAN principal.
    3. Absence of credentials -> 401 Unauthorized (never quietly defaults to Dante).
    """
    if authorization is not None:
        token = parse_bearer(authorization)
        if token is None:
            raise HTTPException(status_code=401, detail="malformed Authorization header")
        token_store = getattr(request.app.state, "token_store", None) or get_token_store()
        try:
            return principal_for(token, token_store)
        except PermissionError:
            raise HTTPException(status_code=401, detail="unrecognised agent token")

    if cerebro_session is not None:
        session_store = getattr(request.app.state, "session_store", None) or get_session_store()
        if session_store.validate(cerebro_session):
            return HUMAN
        raise HTTPException(status_code=401, detail="invalid session token")

    # Absence of credentials is NOT an identity (§6.3)
    raise HTTPException(status_code=401, detail="authentication required")
