"""Identity for Cerebro — who is making this request.

§6.2 established that the server assigns authorship and the caller never claims it. §6.3 adds the
missing half: an external agent needs a way to be *itself*. Without it the only authenticated
identity is the human, so Claude, Antigravity and Codex sit in channels they cannot speak in, and
the tempting shortcut is to let automation borrow Dante's principal — which is impersonation with
a cutover attached.

Design notes worth keeping:

- **An unknown token is rejected, never downgraded.** Falling back to the human principal on a bad
  token would turn a typo into an impersonation, which is precisely the failure this module exists
  to prevent.
- **Comparison is constant-time and scans every token.** Short-circuiting on the first match leaks
  which prefixes are valid through timing.
- **Tokens live in `data/.secrets.env`, never in `profile.json`, the database, an API response or
  a log line.** `redact()` exists so that stays true by construction rather than by vigilance.
"""

import hmac
import os
import secrets
from dataclasses import dataclass
from pathlib import Path

TOKEN_PREFIX = "CEREBRO_AGENT_TOKEN_"
TOKEN_BYTES = 32
HUMAN_ID = "dante"


@dataclass(frozen=True, slots=True)
class Principal:
    """Who the server believes is speaking. Never built from client-supplied data."""

    id: str
    kind: str = "user"  # 'user' | 'agent'
    name: str = "Dante"

    @property
    def is_agent(self) -> bool:
        return self.kind == "agent"

    @property
    def author_kind(self) -> str:
        """What `messages.author_kind` becomes for anything this principal writes."""
        return "agent" if self.is_agent else "user"


HUMAN = Principal(id=HUMAN_ID, kind="user", name="Dante")


def redact(token: str) -> str:
    """Safe to log. Enough to correlate, not enough to use."""
    return f"{token[:4]}…{token[-2:]}" if len(token) > 8 else "…"


def _env_key(agent_id: str) -> str:
    return TOKEN_PREFIX + agent_id.upper().replace("-", "_")


class TokenStore:
    """Agent bearer tokens, in an env file outside version control."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    # -- persistence --------------------------------------------------------------

    def _read(self) -> dict[str, str]:
        """agent_id -> token. A malformed line is skipped rather than fatal."""
        out: dict[str, str] = {}
        try:
            text = self.path.read_text(encoding="utf-8")
        except OSError:
            return out
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            if key.startswith(TOKEN_PREFIX) and value.strip():
                out[key[len(TOKEN_PREFIX):].lower().replace("_", "-")] = value.strip()
        return out

    def _write(self, tokens: dict[str, str]) -> None:
        """Atomic replace: a crash mid-write must not leave every agent unable to authenticate."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Cerebro agent bearer tokens. Never commit this file.",
            "# Generated by `cerebro token issue`; see architecture §6.3.",
        ]
        lines += [f"{_env_key(agent)}={token}" for agent, token in sorted(tokens.items())]
        tmp = self.path.with_suffix(self.path.suffix + ".tmp")
        tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.replace(tmp, self.path)

    # -- operations ---------------------------------------------------------------

    def issue(self, agent_id: str) -> str:
        """Mint a token, replacing any existing one for that agent."""
        token = secrets.token_urlsafe(TOKEN_BYTES)
        tokens = self._read()
        tokens[agent_id] = token
        self._write(tokens)
        return token

    def revoke(self, agent_id: str) -> bool:
        tokens = self._read()
        if agent_id not in tokens:
            return False
        del tokens[agent_id]
        self._write(tokens)
        return True

    def agents(self) -> list[str]:
        """Agent ids holding a token. Deliberately returns no token material."""
        return sorted(self._read())

    def resolve(self, token: str) -> str | None:
        """Return the agent id for a token, or None.

        Scans every entry with a constant-time comparison: returning early on a match would let a
        caller learn valid prefixes from response timing.
        """
        if not token:
            return None
        found: str | None = None
        for agent_id, known in self._read().items():
            if hmac.compare_digest(token, known):
                found = agent_id
        return found


def principal_for(token: str | None, tokens: TokenStore) -> Principal:
    """Resolve an Authorization bearer value to a principal.

    No token means the local human (§D5: we bind to localhost and there is one person here). A
    token that does not resolve raises — it must never quietly become the human.
    """
    if token is None:
        return HUMAN
    agent_id = tokens.resolve(token)
    if agent_id is None:
        raise PermissionError("unrecognised agent token")
    return Principal(id=agent_id, kind="agent", name=agent_id)


def parse_bearer(header: str | None) -> str | None:
    """Extract the token from an Authorization header, or None if absent."""
    if not header:
        return None
    scheme, _, value = header.strip().partition(" ")
    if scheme.lower() != "bearer" or not value.strip():
        return None
    return value.strip()
